### Check server status
Get http://localhost:8000/api/v1

###Get admin user
GET http://localhost:8000/api/v1/admin-user

### get new accessJWT
GET http://localhost:8000/api/v1/admin-user/accessjwt 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFheXVzaEBlbWFpbC5jb20iLCJpYXQiOjE2OTYwMzgxMjAsImV4cCI6MTY5ODYzMDEyMH0.C5-cms1rfHbAQRs9TCJPOHSD991JVmdhuUEHqIDJhjw

###Post new admin user
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "fName":"Aayush",
    "lName":"Bartaula",
    "email":"aayush@email.com",
    "password":"12345678",
    "phone":"0414449540",
    "address":"Sydney",
    "dob":"2022-02-20"
}

###login admin user
POST http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{
   "email":"aayush@email.com",
    "password":"12345678"
}

###Post new admin user
PATCH  http://localhost:8000/api/v1/admin-user/verify-email


###Delete user
DELETE http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
     "ids":[
        "64f80bda338510b8654505ec"
       ] 
}

### <---------------------------------->
### <--------- CATAGORY --------------->
### <---------------------------------->

### Get the available category
GET http://localhost:8000/api/v1/catagory
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFheXVzaEBlbWFpbC5jb20iLCJpYXQiOjE2OTYwMzgxMjAsImV4cCI6MTY5NjAzOTAyMH0.fgbzwkOe-g90k8TSVMuiCslXPW1BUsAouRd6xHRH3X4

### GET CATAGORY
POST http://localhost:8000/api/v1/catagory
Content-Type: application/json 

{
    "status":"active",
    "name":"Laptop",
    "parentId":""
}

### delete CATAGORY
DELETE http://localhost:8000/api/v1/catagory
Content-Type: application/json 

{
     "ids":[
             "6502c64fc8038573e5525273"
            ] 
}


### <---------------------------------->
### <--------- Payment --------------->
### <---------------------------------->

###get payment
GET http://localhost:8000/api/v1/paymentMethod


###post payment
POST http://localhost:8000/api/v1/paymentMethod
Content-Type: application/json

{
    "status":"inactive",
    "name":"Apple Pay",
    "description":"Follow the instruction to add apple pay"
}

###update payment and its description
PUT http://localhost:8000/api/v1/paymentMethod
Content-Type: application/json

{
    "_id":"651f54739100700e64ef737f",
    "status":"active",
    "name":"Pay by credit card",
    "description":"Follow the instruction because Amex is not accepted"
}
###delete payment 
DELETE http://localhost:8000/api/v1/paymentMethod
Content-Type: application/json

{
    "_id":"6523c592486974b20a5e0ce0"
}